### ISSUE TITLE
MM/DD anstatt DD/MM

### ISSUE THREAD

**Issue by Leiko3** [berlinux2016/MIUI12#12]
- **MIUI Version:** 12.0.1
- **Gerätename:** Mi 10 Pro

Die Datumsanzeige nutzt das US-System von Monat/Tag

![Screenshot_2020-08-06-22-11-32-132_lockscreen](https://user-images.githubusercontent.com/69323741/89578443-6dc7da80-d832-11ea-853c-12768d6e0b84.jpg)
![Screenshot_2020-08-06-22-11-49-544_lockscreen](https://user-images.githubusercontent.com/69323741/89578447-6e607100-d832-11ea-91c3-a33e4fbffc39.jpg)

**Comment by MeiGuddet** [comment]
Die strings sind inzwischen alle angepasst. Es liegt wahrscheinlich daran, dass du noch eine ältere ROM hast. Warte bitte mal noch auf das nächste Update.
