### ISSUE TITLE
Error in Info Assistent / App VAULT NEWS in polish and Not installed language

### ISSUE THREAD

**Issue by 69reichertm** [berlinux2016/MIUI12#13]
I installed the latest App Vault Update sich gives more functions. The installed Version is crap.

With the latest Update many News Features and they Show Up all in German.

Only the News Feed is still in polish or so.

Please Change it that it gets German news

- newest Mui 12 EU

- Mi 10 Pro 

**Screenshot/Description:**

**Comment by MeiGuddet** [comment]
Das hat dir schon jemand im eu-Forum beantwortet: Du benutzt nicht den in der ROM enthaltenen übersetzten App Vault, sondern hast die globale Version. Diese hat nichts mit uns zu tun und wird nicht von uns übersetzt.

**Comment by 69reichertm** [comment]
Und wer macht das dann ?
Es ist ja alles übersetzt  bis auf die Nachrichten.
Danke für die Info.
Viele Grüße
Am 18.08.2020 um 15:55 schrieb MeiGuddet <notifications@github.com>:

﻿

Das hat dir schon jemand im eu-Forum beantwortet: Du benutzt nicht den in der ROM enthaltenen übersetzten App Vault, sondern hast die globale Version. Diese hat nichts mit uns zu tun und wird nicht von uns übersetzt.

**Comment by MeiGuddet** [comment]
Das ist bereits übersetzt, sonst wäre es nicht polnisch. Diesen App Vault kann man nur auf der globalen ROM nutzen, da man dort die Region auf Deutsch umstellen kann. Das geht in der eu-ROM nicht, dort ist die Region nicht änderbar auf Polen voreingestellt, damit alle Patches/Systemeinstellungen funktionieren.

**Comment by 69reichertm** [comment]
Die App an sich ist ja komplett in Deutsch.
Nur der Inhalt der Nachrichten ist Polnisch.
Ist ja echt schade.
Die deutsche Version von dem App Vault hat ja quasi keine Funktionen und ist sinnfrei.
Die Global finde ich total gut. Mist. Ausgerechnet Polnisch. Warum nicht English. Das kann man wenigstens.

Dann muss ich den Google Feed nehmen aber der ruckelt so und hat wenig Funktionen.

Danke für die Info.
Total nett !!!

Ansonsten super Arbeit !

Lg Marcus

Am 18.08.2020 um 16:09 schrieb MeiGuddet <notifications@github.com>:

﻿

Das ist bereits übersetzt, sonst wäre es nicht polnisch. Diesen App Vault kann man nur auf der globalen ROM nutzen, da man dort die Region auf Deutsch umstellen kann. Das geht in der eu-ROM nicht, dort ist die Region nicht änderbar auf Polen voreingestellt, damit alle Patches/Systemeinstellungen funktionieren.

**Comment by MeiGuddet** [comment]
Kannst ja mal versuchen, ob es mit der App MoreLocale funktioniert, ihn auf Deutsch umzustellen. Kann aber sein, dass du Root dafür brauchst.

**Comment by Henry2o1o** [comment]
Hast du Root, kannst du auch den Cust-Ordner einfügen und dann die Region andern.

**Comment by 69reichertm** [comment]
Oh was ist denn der cust Ordner ?


Gesendet über BlackBerry Hub+ Posteingang für Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
Von: notifications@github.com
Gesendet: 18. August 2020 18:12
An: MIUI12@noreply.github.com
Antworten: reply@reply.github.com
Cc: reichertm@live.de; author@noreply.github.com
Betreff: Re: [berlinux2016/MIUI12] Error in Info Assistent / App VAULT NEWS in polish and Not installed language (#13)


Hast du Root, kannst du auch den Cust-Ordner einfügen und dann die Region andern.

**Comment by Henry2o1o** [comment]
Der Ordner mit allen Regionen.

**Comment by 69reichertm** [comment]
Und wo finde ich den ?
Ist der von App Vault oder Android ?

Ich habe leider keine Ahnung.
Danke aber schon Mal !
Total nett

Gesendet über BlackBerry Hub+ Posteingang für Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
Von: notifications@github.com
Gesendet: 18. August 2020 18:24
An: MIUI12@noreply.github.com
Antworten: reply@reply.github.com
Cc: reichertm@live.de; author@noreply.github.com
Betreff: Re: [berlinux2016/MIUI12] Error in Info Assistent / App VAULT NEWS in polish and Not installed language (#13)


Der Ordner mit allen Regionen.
