### ISSUE TITLE
Fehlende Übersetzung im Fokus Modus

### ISSUE THREAD

**Issue by Michiiib3** [berlinux2016/MIUI12#15]
Wenn der Fokus Modus beendet wird und die Auswertung erscheint, erscheinen noch viele chinesische Symbole. Was die jetzt genau bedeuten weiß ich nicht. 

![IMG_20200917_112346](https://user-images.githubusercontent.com/65068089/95014387-c0611f80-0646-11eb-9aa8-bdde821a2200.jpg)

- **MIUI Version:** 12.1.3.
- **Device name:** Mi 10 pro 

**Screenshot/Description:**

**Comment by Henry2o1o** [comment]
Global ?

**Comment by MeiGuddet** [comment]
@Michiiib3 Bist du auf der eu custom ROM? Wenn nicht, bist du hier verkehrt.

**Comment by Henry2o1o** [comment]
[Update] [Android 11] [MIUI 12.1.3] xiaomi.eu stable Rom

könnte diese sein ?

**Comment by Henry2o1o** [comment]
MIUI Version: 12.1.3.
https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/MIUI-STABLE-RELEASES/MIUIv12/

**Comment by Henry2o1o** [comment]
> @Michiiib3 Bist du auf der eu custom ROM? Wenn nicht, bist du hier verkehrt.

xiaomi.eu_multi_MI10Pro_V12.1.3.0 Stable

**Comment by Michiiib3** [comment]
> > @Michiiib3 Bist du auf der eu custom ROM? Wenn nicht, bist du hier verkehrt.
> 
> xiaomi.eu_multi_MI10Pro_V12.1.3.0 Stable

Genau auf der bin ich. Also bin ich hier denke ich richtig.

**Comment by Henry2o1o** [comment]
> > > @Michiiib3 Bist du auf der eu custom ROM? Wenn nicht, bist du hier verkehrt.
> > 
> > 
> > xiaomi.eu_multi_MI10Pro_V12.1.3.0 Stable
> 
> Genau auf der bin ich. Also bin ich hier denke ich richtig.

👍

**Comment by MeiGuddet** [comment]
> 
> 
> > > @Michiiib3 Bist du auf der eu custom ROM? Wenn nicht, bist du hier verkehrt.
> > 
> > 
> > xiaomi.eu_multi_MI10Pro_V12.1.3.0 Stable
> 
> Genau auf der bin ich. Also bin ich hier denke ich richtig.

Vergiss meinen Post. Nachdem @Henry2o1o seinen Post komplett geändert hat, fehlt der Kontext, sorry.

**Comment by Henry2o1o** [comment]
bei 20 Minuten

![image](https://user-images.githubusercontent.com/6131799/95020464-979f5100-066b-11eb-83af-858e2d91f1c9.png)

**Comment by MeiGuddet** [comment]
@Michiiib3 Passt es jetzt`? Dann kann ich hier zumachen.
