### ISSUE TITLE
Wrong dateformat on AOD screen

### ISSUE THREAD

**Issue by amas277** [berlinux2016/MIUI12#16]
MIUI Version: 20.10.15
Device name: Mi9TPro

Dateformat on AOD-screen "10/17" is wrong. The correct format is "17.10."

**Comment by MeiGuddet** [comment]
Ok, sehe ich mir an.

**Comment by amas277** [comment]
Ja, ich bin auf der xiaomi.eu 20.10.15. Ich habe jetzt die Superhintergründe Mars und Erde versucht und das Datumsformat im AOD-screen ist "MM/DD". Am lockscreen passt es: "DD.MM." 
Wie macht man einen screenshot vom AOD-screen?

**Comment by Henry2o1o** [comment]
Mars & Erde sind übersetzt, ich habe Saturn getestet 

![image](https://user-images.githubusercontent.com/6131799/96372541-9724b100-1167-11eb-8bb2-602b62824d56.png)

**Comment by MeiGuddet** [comment]
> Wie macht man einen screenshot vom AOD-screen?

Versuch mal 3-Finger-Wischen nach unten oder Ein-/Aus-Taste einige Sekunden lang gedrückt halten und dann auf Screenshot tippen oder Ein-/Aus-Taste und die Leisertaste gleichzeitig mehrere Sekunden lang gedrückt halten.

**Comment by Henry2o1o** [comment]
funktioniert da nicht

**Comment by Henry2o1o** [comment]
Erde & Mars, wo sind die beiden Apk's her?
Vermutlich werden unsere Übersetzung bei diesen beiden Apk's nicht hinzugfügt?

**Comment by MeiGuddet** [comment]
Die APK's gehören aber nicht zur ROM, sind extern.

**Comment by Henry2o1o** [comment]
ja eben und deshalb passt wohl die Übersetzung nicht

**Comment by Henry2o1o** [comment]
ich habe eine MiuiWallpaper.apk da ist der Saturn schon mit drinnen

**Comment by MeiGuddet** [comment]
Warum sollten sie auch? Sie gehören nicht in die ROM.
Hab den nicht angepassten string gefunden, glaube ich.

**Comment by amas277** [comment]
Dateformat is ok in 20.10.22
Thanks.
