### ISSUE TITLE
Dateformat not german convention

### ISSUE THREAD

**Issue by HTransistor** [berlinux2016/MIUI12#17]
MIUI Version: 20.11.12
Device name: Mi9T

Dateformat on AOD-screen "10/17" is wrong. The correct format is "17.10."

Same issue as #16, but for the newest ROM.

**Comment by MeiGuddet** [comment]
Lade bitte mal einen Screenshot hoch.

**Comment by HTransistor** [comment]
Ja, bin ich.
Ich habe aber auch die Systemsprache auf Englisch, trotzdem gibt es die Option nicht in den Einstellungen das deutsche Zeitformat zuwählen.
![Screenshot_2020-11-15-20-06-49-417_lockscreen](https://user-images.githubusercontent.com/43704364/99194557-5f1d8780-2780-11eb-9561-25e15a4b1d66.jpg)

**Comment by MeiGuddet** [comment]
Benutzt du die SuperWallpaperMars? Vermutlich liegt es an der apk. Die SuperWallpaper-apk übersetzen wir hier nicht, sind kein Bestandteil der ROM.

**Comment by HTransistor** [comment]
Ja, die nutze ich. Da die direkt von der ROM in den Einstellungen angegeben war, dachte ich das gehört dazu, sorry.
