### ISSUE TITLE
Clipboard Access Warning in chinese

### ISSUE THREAD

**Issue by chrissammy** [berlinux2016/MIUI12#19]
- **MIUI Version:** 20.12.2
- **Device name:** Mi 9

**Screenshot/Description:**
The Clipboard App Access Warnung is in Chinese.

When I want to copy from one app into another app. Then popup comes up with chinese language.
![Screenshot_2020-12-10-22-20-41-631_com opera touch](https://user-images.githubusercontent.com/67926674/101831319-0a2e2080-3b36-11eb-91cb-75687202c925.jpg)

**Comment by MeiGuddet** [comment]
Sollte gefixt sein mit der 20.12.9/10. Wenn nicht, probier mal clear data in der Sicherheit-App.

**Comment by chrissammy** [comment]
> @chrissammy Sollte gefixt sein mit der 20.12.9/10. Wenn nicht, probier mal clear data in der Sicherheit-App.

Ja, ist gefixed.

**Comment by chrissammy** [comment]
Close
