### ISSUE TITLE
Galerie

### ISSUE THREAD

**Issue by darki15** [berlinux2016/MIUI12#21]
Hallo

Mi9 mit 20.12.28

Galerie: Fotos - Alben - Recommended

Letzteres muss noch übersetzt werden.

**Comment by MeiGuddet** [comment]
Bin schon seit Stunden dran.  Da gibt es noch sehr viele neue englische strings.

**Comment by MeiGuddet** [comment]
In Bearbeitung...

**Comment by MeiGuddet** [comment]
Erledigt.
