### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by nikai90** [berlinux2016/MIUI12#24]
![IMG_20210124_081923](https://user-images.githubusercontent.com/77916286/105625173-9d41c200-5e27-11eb-8fc3-b7ef8f69ea6a.jpg)

- **MIUI Version:** 21.1.20
- **Device name:** Mi 9

**Screenshot/Description:**

**Comment by MeiGuddet** [comment]
Schon erledigt https://github.com/berlinux2016/MIUI12/commit/1fc7a2ed00e2f7520eb96dcb7396685aa44efed3. 
Hab's eben im Forum gelesen.
