### ISSUE TITLE
Translation "Reverse Charging"

### ISSUE THREAD

**Issue by Maximowic** [berlinux2016/MIUI12#26]
- **MIUI Version:** 12.5.7
- **Device name:** Mi 11

**Screenshot/Description:**
The Translation for "Reverse charging" -> "Kabelloses Laden rückgängig machen" is not correct. The correct translation were"Umkehrladen aktivieren"
![Screenshot](https://user-images.githubusercontent.com/84839290/119627777-cc376700-be0c-11eb-8f7d-b369b8ac7c9a.jpg)

**Comment by MeiGuddet** [comment]
Korrigiert c4f676733
