### ISSUE TITLE
Spotify/Musicplayer invisible notification

### ISSUE THREAD

**Issue by Maximowic** [berlinux2016/MIUI12#27]
- **MIUI Version:** 12.5.7
- **Device name:** Mi 11 Ultra

**Screenshot/Description:**
Hello together, i got this issue with invisible/nonswipeable notification after spotify.
This workaround didnt help me: https://xiaomi.eu/community/threads/21-5-12-13.61262/post-607715
Is there a way to fix it by my self or is it an issue which will correct in the new update of Miui?

kindly,
Max
![invisible](https://user-images.githubusercontent.com/84839290/120981560-10fdbf00-c778-11eb-86c1-a63deee15032.jpg)

**Comment by MeiGuddet** [comment]
Hier geht es rein um die deutsche Übersetzung, wir sind nicht für Bugs/Issues zuständig.
