### ISSUE TITLE
Obsolete APKs?

### ISSUE THREAD

**Issue by MeiGuddet** [berlinux2016/MIUI12#34]
@ingbrzy @IgorEisberg
Can they be deleted for upcoming releases with A12 yes or no?
1. All AccentColor*.apk
2. AppIndexProvider.apk
3. ~~BlockedNumberProvider.apk~~
4. ~~BookmarkProvider.apk~~
5. BackupRestoreConfirmation.apk
6. BlockedNumberProvider.apk
7. BookmarkProvider.apk
8. Browser.apk
9. BTProductionLineTool.apk
10. BtTool.apk
11. BugReport.apk
12. CellBroadcastReceiver.apk
13. All DisplayCutoutEmulation*.apk
14. DocumentsUI.apk
15. EmergencyInfo.apk
16. FashionGallery.apk
17. GameCenter.apk
17. GameCenterGlobal.apk
18. GFTest.apk
19. greenguard.apk
20. HybridAccessory.apk
21. HybridPlatform.apk
22. All IconShape*.apk
23. ~~imssettings.apk~~
24. KeyChain.apk
25. LiveWallpapersPicker.apk
26. MediaFeature.apk
27. MediaProvider.apk
28. mediatek-res.apk
29. MetokNLP.apk
30. MiDrop.apk
31. MiMediaEditor.apk
32. MiMoverGlobal.apk
33. Mipay.apk
34. MiPlay.apk
35. MIUI_Registration_MIUI-12.apk
36. MiuiAccessibility.apk
37. MiuiDaemon.apk
38. MiuiKeyguard.apk
39. MiuiPrintSpoolerBeta.apk
40. MiuiTelecomOverlay.apk
41. MiuiVideo.apk
42. MiuiVideoLeo.apk
43. MtkTeleService.apk
44. MtpDocumentsProvider.apk
45. MusicFX.apk
46. Omacp.apk
47. PermissionController.apk
48. PowerChecker.apk
49. Protips.apk
50. SecurityInputMethod.apk
51. SmsExtra.apk
52. SpacesPolicyApp.apk
53. StorageManager.apk
54. ThirdAppAssistant.apk
55. WallpaperCropper.apk
56. WeatherProvider.apk
57. WfdService.apk
58. Whetstone.apk
59. XiaomiAuthenticator.apk
60. XiaomiEUTools.apk
61. XMCloudEngine.apk
62. XMRemoteController.apk
63. YellowPage.apk
64. Zman.apk

**Comment by ingbrzy** [comment]
yes, obsolete..

**Comment by MeiGuddet** [comment]
Thank you.
