### ISSUE TITLE
Mi Mail language

### ISSUE THREAD

**Issue by pittrich67** [berlinux2016/MIUI12#35]
![Screenshot_2021-09-20-16-24-57-116_com android email](https://user-images.githubusercontent.com/11316615/134019537-2c0d9d36-a918-4f9c-ae95-13bfb9cd728d.jpg)

- **MIUI Version:** X.X.X
- **Device name:** Mi XYZ

**Screenshot/Description:**

MIUI weekly 21.9.1
Mi 11 (M2011K2C)
The description for "Current Mailbox" is in Chinese

**Comment by MeiGuddet** [comment]
@pittrich67 Danke für den Hinweis. Ist aber bereits übersetzt seit 02.09. Du hast aber noch keine aktuell ROM.
