### ISSUE TITLE
Bevorzugter netzwerktyp 

### ISSUE THREAD

**Issue by Michiiib3** [berlinux2016/MIUI12#5]
Beim bevorzugten Netzwerktyp ist bei lte ein Rechtschreibfehler. 

Siehe Bild 

Xiaomi.eu 20.5.24 mi 10 pro

![IMG_20200612_114939](https://user-images.githubusercontent.com/65068089/84489984-cfd8e900-aca2-11ea-9e3a-59521b16392c.jpg)

**Comment by MeiGuddet** [comment]
Ist bereits seit Sa 06.06. korrigiert
https://github.com/berlinux2016/MIUI12/commit/004a2702fae145d7213dcc52e459d07c9881573f
