### ISSUE TITLE
Superhintergründe Crashing

### ISSUE THREAD

**Issue by vcdwelt** [berlinux2016/MIUI12#6]
- **MIUI Version:** V12.0.1.0.QFACNXM
- **Device name:** Mi 9 (Cepheus) 

**Screenshot/Description:**
When opening: 
Einstellungen -> Hintergrund -> Superhintergründe 
it crashes back to settings. With English language all is fine.

**Comment by Henry2o1o** [comment]
Ich habe das Mi Note 10, da ist alles ok.

**Comment by vcdwelt** [comment]
Grundsätzlich funktionieren die Hintergründe beide. Ich kann sie z.B. über meinen Launcher auswählen und setzen.
Es geht explizit um den weg über die Einstellungen. Wenn ich dort die Superhintergründe auswähle schliesst sich das Fenster direkt wieder. Sobald ich das Gerät auf Englisch stelle, kann ich das Menü öffnen.

Hier noch der Crashlog, vielleicht hilft das weiter...
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValueForDensity(Unknown Source:32)
	at android.content.res.Resources.getDrawableForDensity(Unknown Source:8)
	at android.content.res.Resources.getDrawable(Unknown Source:1)
	at android.content.res.Resources.getDrawable(Unknown Source:1)
	at com.miui.miwallpaper.widget.SuperWallpaperItem.setBaseContents(Unknown Source:57)
	at com.miui.miwallpaper.activity.SuperWallpaperListActivity$1.onPostExecute(Unknown Source:208)
	at com.miui.miwallpaper.activity.SuperWallpaperListActivity$1.onPostExecute(Unknown Source:2)
	at android.os.AsyncTask.finish(Unknown Source:10)
	at android.os.AsyncTask.access$900(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:28)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

**Comment by Henry2o1o** [comment]
![image](https://user-images.githubusercontent.com/6131799/84878569-49e5e500-b08a-11ea-9a4c-f3cb2f23554a.png)
![image](https://user-images.githubusercontent.com/6131799/84878576-4ce0d580-b08a-11ea-9b4d-5c9ed8d6790d.png)

**Comment by vcdwelt** [comment]
Sehr merkwürdig. Ich denke es wird Zeit das Rom nochmal neu zu installieren, es gab heute morgen sowieso nochmal einen neuen Upload, vielleicht funktioniert es dann.

**Comment by Henry2o1o** [comment]
die Übersetzungen sind ja die gleichen 🤷‍♂️

**Comment by vcdwelt** [comment]
Ok, auch nach dem neusten Fix Release von heute morgen gleiches Problem :-( 
Sprache auf deutsch FC, auf englisch einwandfrei. Noch irgendwelchen Ideen, was ich machen oder welche Logs ich liefern könnte? Im Forum gibt es noch ein paar andere mit dem gleichen Problem...

[Screenrecorder-2020-06-17-12-46-47-391.zip](https://github.com/berlinux2016/MIUI12/files/4791982/Screenrecorder-2020-06-17-12-46-47-391.zip)

**Comment by Henry2o1o** [comment]
Seltsam, ich habe es wie schon gesagt nicht.

**Comment by MeiGuddet** [comment]
Kein es bei mir nicht testen, da mein Mi 9T Superhintergründe nicht unterstützt.

**Comment by MeiGuddet** [comment]
Lt. eu-Forum war es ein Bug und wurde behoben:

**Comment by ingbrzy** [comment]
not a translation issue.. 
Stable ROMs reuploaded with fixed this bug..

**Comment by vcdwelt** [comment]
Ich hatte bereits die von Ingbrzy erwähnte Version von heute vormittag installiert. Zur sicherheit habe ich sie gerade eben nochmal geladen (von beiden Anbietern um einen Fehlerhaften Upload auszuschließen) und geflasht. Habe aber weiterhin genau das gleiche Problem.

Was mich eben wundert, wenn ich das Handy auf englisch stelle, geht es einwandfrei...

**Comment by malchik-solnce** [comment]
Darf ich einmal miwallpaper.apk haben?😀

**Comment by malchik-solnce** [comment]
> Kein es bei mir nicht testen, da mein Mi 9T Superhintergründe nicht unterstützt.

wenn du möchtest, kannst probieren: MiWallpaper - system/app/MiWallpaper. https://yadi.sk/d/8tqXXH7Nxwg6Jg

**Comment by malchik-solnce** [comment]
> Ich hatte bereits die von Ingbrzy erwähnte Version von heute vormittag installiert. Zur sicherheit habe ich sie gerade eben nochmal geladen (von beiden Anbietern um einen Fehlerhaften Upload auszuschließen) und geflasht. Habe aber weiterhin genau das gleiche Problem.
> 
> Was mich eben wundert, wenn ich das Handy auf englisch stelle, geht es einwandfrei...

Darf ich einmal miwallpaper.apk haben? 😀 oder versuch mal zu installieren https://yadi.sk/d/NlCs4n_mH-eSIg

**Comment by vcdwelt** [comment]
> > Ich hatte bereits die von Ingbrzy erwähnte Version von heute vormittag installiert. Zur sicherheit habe ich sie gerade eben nochmal geladen (von beiden Anbietern um einen Fehlerhaften Upload auszuschließen) und geflasht. Habe aber weiterhin genau das gleiche Problem.
> > Was mich eben wundert, wenn ich das Handy auf englisch stelle, geht es einwandfrei...
> 
> Darf ich einmal miwallpaper.apk haben? 😀 oder versuch mal zu installieren https://yadi.sk/d/NlCs4n_mH-eSIg

Kann ich leider nicht installieren. Es kommt der Fehler, das ich keine Systemapps aus unsicheren Quellen installieren kann.
Wie komme ich an meine miwallpaper.apk? Habe mein Smartphone nicht gerootet.

**Comment by Henry2o1o** [comment]
gar nicht

**Comment by Henry2o1o** [comment]
> Lt. @ingbrzy im eu-Forum war es ein Bug und wurde behoben:
> [https://xiaomi.eu/community/threads/super-wallpaper-crashing.56222/#post-548754](url)

wo führt der link hin?

**Comment by vcdwelt** [comment]
> > Lt. @ingbrzy im eu-Forum war es ein Bug und wurde behoben:
> > [https://xiaomi.eu/community/threads/super-wallpaper-crashing.56222/#post-548754](url)
> 
> wo führt der link hin?

[](https://xiaomi.eu/community/threads/super-wallpaper-crashing.56222/)

**Comment by vcdwelt** [comment]
> > Lt. @ingbrzy im eu-Forum war es ein Bug und wurde behoben:
> > [https://xiaomi.eu/community/threads/super-wallpaper-crashing.56222/#post-548754](url)
> 
> wo führt der link hin?

[https://xiaomi.eu/community/threads/super-wallpaper-crashing.56222/](url)

**Comment by vcdwelt** [comment]
Ok, ganz vergessen, ich kann ja im TWRP die System Partition mounten :)
Habe die Apk ersetzt, jetzt sieht es zwar anders aus als vorher (ganz andere Optik), aber es stürzt nichts mehr ab.

Hier noch meine MiWallpaper.apk:
https://1drv.ms/u/s!AjSxmC8ZbPA3iJFMdBSX0oyMa0RxNg?e=ztMMIl

**Comment by Henry2o1o** [comment]
Ja mit TWRP geht's natürlich auch.

**Comment by malchik-solnce** [comment]
> Ok, ganz vergessen, ich kann ja im TWRP die System Partition mounten :)
> Habe die Apk ersetzt, jetzt sieht es zwar anders aus als vorher (ganz andere Optik), aber es stürzt nichts mehr ab.
> 
> Hier noch meine MiWallpaper.apk:
> https://1drv.ms/u/s!AjSxmC8ZbPA3iJFMdBSX0oyMa0RxNg?e=ztMMIl

ja, habe da was geändert, so ist doch besser:)
