### ISSUE TITLE
Macromodus Kamera 

### ISSUE THREAD

**Issue by Michiiib3** [berlinux2016/MIUI12#7]
- **MIUI Version:** 20.6.18 
- **Device name:** Mi 10 pro 

**Screenshot/Description:**

Als ich gerade eine Spinne fotografieren wollte, erschien der schriftzug in der Mitte und die Kamera schaltete automatisch auf die makro Linse. 
Laut Google übersetzter bedeutet das makromodus.

Software 20.6.18 auf dem mi 10 pro
![Screenshot_2020-06-21-17-54-22-367_com android camera](https://user-images.githubusercontent.com/65068089/85229204-c6f5bf00-b3e8-11ea-9272-ee5d8a0f73bc.jpg)

**Comment by Henry2o1o** [comment]
Wurde schon übersetzt, vermutlich zu spät. Ist dann in der nächsten Version vorhanden.
